### ISSUE TITLE
The model_urls are broken

### ISSUE THREAD

**Issue by iDTer** [nizhib/pytorch-insightface#8]
The model_urls = {
    'iresnet34': 'https://sota.nizhib.ai/pytorch-insightface/iresnet34-5b0d0e90.pth',
    'iresnet50': 'https://sota.nizhib.ai/pytorch-insightface/iresnet50-7f187506.pth',
    'iresnet100': 'https://sota.nizhib.ai/pytorch-insightface/iresnet100-73e07ba7.pth'
} are broken,
could you please update the urls or give the new way to downloading the models.
Thank you very much!

**Comment by iDTer** [comment]
Or you can upload models to Google drive, anyway thanks :D

**Comment by nizhib** [comment]
I've disabled them because of the storage traffic spikes I had to pay too much for.

You can download the old mxnet weights from https://github.com/deepinsight/insightface/tree/master/model_zoo (R100 mxnet link in the table) and use the scripts provided in my repo to convert them.
